[CI/CD] creation of release with .zip and .targz for the code

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -11,18 +11,64 @@ on:
     branches-ignore:
       - 'skip-ci-*'
     
+permissions:
+  contents: write
+    
 env:
     REPOSITORY_MIRROR: "git@github.com:EpitechPromo2027/B-FUN-500-NAN-5-2-glados-florent.charpentier.git"
 
 jobs:
-  print-branch-names:
+  can-merge-pr:
     if: ${{ github.event_name == 'pull_request' }}
     runs-on: ubuntu-latest
     steps:
-      - name: Print Branch Names
+      - name: Check branchs names
         run: |
-          echo "Source branch (head): ${{ github.event.pull_request.head.ref }}"
-          echo "Target branch (base): ${{ github.event.pull_request.base.ref }}"
+          source=${{ github.event.pull_request.head.ref }}
+          target=${{ github.event.pull_request.base.ref }}
+          if [ $source == $target ]; then
+            echo "Branches are the same"
+            exit 1
+          fi
+          if [ "$target" == "main" ] && [[ "$source" != "Release"* ]]; then
+            echo "You can't merge into main from a branch that is not a release branch"
+            exit 1
+          fi
+      - name: Delete Existing Release (if any)
+        if: startsWith(${{ github.event.pull_request.head.ref }}, 'Release')
+        run: |
+          release_id=$(curl -s \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.pull_request.head.ref }} \
+            | jq -r '.id')
+          
+          if [ "$release_id" != "null" ]; then
+            echo "Existing release found. Deleting release ID: $release_id"
+            curl -X DELETE \
+              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+              -H "Accept: application/vnd.github.v3+json" \
+              https://api.github.com/repos/${{ github.repository }}/releases/$release_id
+          else
+            echo "No existing release found for tag: ${{ github.event.pull_request.head.ref }}"
+          fi
+
+      - name: Create Release
+        if: startsWith(${{ github.event.pull_request.head.ref }}, 'Release')
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ github.event.pull_request.head.ref }}
+          release_name: ${{ github.event.pull_request.head.ref }}
+          body: |
+            ${{ github.event.pull_request.body}}
+          draft: false
+          prerelease: false
+
+
+
   build:
     runs-on: ubuntu-latest
 
@@ -31,6 +77,14 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+
+      - name: Build
+        run: |
+          make
+          if [ $? -ne 0 ]; then
+            echo "Build failed"
+            exit 1
+          fi
 
   tests:
     needs: build
